import React, { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, BellRing, CheckCircle2, Eye, Flag, Languages, RefreshCw, Scale, Send, ShieldCheck, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { api } from "../../../lib/api.js";
import { useLang } from "../../../contexts/LanguageContext.jsx";

export default function GovernancePage() {
  const { lang, t } = useLang();
  const [overview, setOverview] = useState(null);
  const [reports, setReports] = useState([]);
  const [analytics, setAnalytics] = useState(null);
  const [notifications, setNotifications] = useState([]);
  const [previewRole, setPreviewRole] = useState("guest");
  const [rolePreview, setRolePreview] = useState(null);
  const [state, setState] = useState("loading");
  const copy = useMemo(() => lang === "en" ? {
    title: "Experience Governance", subtitle: "Review content quality, trust reports, notifications, funnel performance, and fair partner exposure.", quality: "Quality & stale-data queue", attention: "Partner SLA & revisions", reports: "Reports & moderation", delivery: "Notification delivery", analytics: "Funnel & exposure", plannerAnalytics: "AI Planner funnel", preview: "View as role", stale: "Stale", completeness: "complete", missing: "Missing", openId: "Preview ID", openEn: "Preview EN", direct: "Public link", edit: "Edit", publish: "Publish reviewed", revision: "Needs revision", notify: "Send reminder", noData: "No items need attention.", investigate: "Investigate", resolve: "Resolve", dismiss: "Dismiss", hide: "Hide content", days: "Last 30 days", consent: "Only consented analytics are included. Trip stories and preferences are never collected.", roleHint: "Read-only capability preview; the admin session and authorization remain unchanged.", routes: "Visible routes", capabilities: "Capabilities", restrictions: "Restrictions", refresh: "Refresh", sent: "Reminder queued with delivery status.", published: "Editorial workflow updated.", moderated: "Report updated.", directory: "Directory discovery", ai: "AI recommendations", contacts: "Partner contacts", profile: "Profile views", profileClicks: "Profile clicks", featured: "Featured", regular: "Regular", storySubmitted: "Stories submitted", stepShown: "Steps shown", stepCompleted: "Steps completed", generated: "Plans generated", structuredHealth: "Structured result health", structuredRequests: "Structured requests", structuredSuccess: "Structured success", fallbacks: "Fallbacks", invalidRate: "Invalid rate", invalidAlert: "Structured result invalid rate exceeded the alert threshold.", rolloutRollback: "Rollback structured results is recommended. Disable the global Structured V2 flag while investigating.", p95Duration: "P95 duration", p95Payload: "P95 payload", fairness: "Fairness audit", segments: "Exposure by partner type and tier", gaps: "Empty results by area and service type", imageAudit: "Image exposure audit", rankingPolicy: "Ranking policy", noSensitive: "No sensitive attributes or premium tier are used as ranking signals.", score: "Relevance score", factors: "Match factors", overexposed: "Potential overexposure", balanced: "No concentration alert detected.", area: "Area", type: "Type", emptyResults: "Empty results",
  } : {
    title: "Governance Pengalaman", subtitle: "Tinjau kualitas konten, laporan trust, notifikasi, funnel, dan pemerataan exposure Mitra.", quality: "Antrean kualitas & data stale", attention: "SLA & revisi Mitra", reports: "Laporan & moderasi", delivery: "Status pengiriman notifikasi", analytics: "Funnel & exposure", plannerAnalytics: "Funnel AI Planner", preview: "Lihat sebagai role", stale: "Kedaluwarsa", completeness: "lengkap", missing: "Kurang", openId: "Preview ID", openEn: "Preview EN", direct: "Link publik", edit: "Edit", publish: "Terbitkan setelah review", revision: "Perlu revisi", notify: "Kirim pengingat", noData: "Tidak ada item yang membutuhkan perhatian.", investigate: "Investigasi", resolve: "Selesaikan", dismiss: "Tolak laporan", hide: "Sembunyikan konten", days: "30 hari terakhir", consent: "Hanya analitik dengan consent yang dihitung. Isi cerita dan preferensi perjalanan tidak pernah dikumpulkan.", roleHint: "Preview kemampuan bersifat read-only; sesi dan authorization admin tidak berubah.", routes: "Route terlihat", capabilities: "Kemampuan", restrictions: "Pembatasan", refresh: "Muat ulang", sent: "Pengingat masuk antrean beserta status pengiriman.", published: "Workflow editorial diperbarui.", moderated: "Laporan diperbarui.", directory: "Discovery direktori", ai: "Rekomendasi AI", contacts: "Kontak Mitra", profile: "Profil dilihat", profileClicks: "Klik profil", featured: "Unggulan", regular: "Reguler", storySubmitted: "Cerita dikirim", stepShown: "Langkah ditampilkan", stepCompleted: "Langkah diselesaikan", generated: "Rencana dibuat", structuredHealth: "Kesehatan structured result", structuredRequests: "Permintaan structured", structuredSuccess: "Structured berhasil", fallbacks: "Fallback", invalidRate: "Rasio invalid", invalidAlert: "Rasio structured result invalid melewati ambang alert.", rolloutRollback: "Rollback structured result direkomendasikan. Matikan flag global Structured V2 selama investigasi.", p95Duration: "Durasi P95", p95Payload: "Payload P95", fairness: "Audit fairness", segments: "Exposure per tipe dan tier Mitra", gaps: "Hasil kosong per wilayah dan tipe layanan", imageAudit: "Audit exposure gambar", rankingPolicy: "Kebijakan ranking", noSensitive: "Atribut sensitif dan tier premium tidak digunakan sebagai sinyal ranking.", score: "Skor relevansi", factors: "Faktor kecocokan", overexposed: "Potensi exposure berlebih", balanced: "Tidak ada alert konsentrasi.", area: "Wilayah", type: "Tipe", emptyResults: "Hasil kosong",
  }, [lang]);
  const load = useCallback(async () => { setState("loading"); try { const [{ data: overviewData }, { data: reportData }, { data: analyticsData }, { data: deliveryData }] = await Promise.all([api.get("/admin/governance/overview"), api.get("/admin/governance/reports", { params: { status: "all" } }), api.get("/admin/governance/analytics"), api.get("/admin/governance/notifications")]); setOverview(overviewData); setReports(reportData); setAnalytics(analyticsData); setNotifications(deliveryData); setState("ready"); } catch { setState("error"); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { api.get(`/admin/governance/role-preview/${previewRole}`).then(({ data }) => setRolePreview(data)).catch(() => setRolePreview(null)); }, [previewRole]);
  const workflow = async (item, status) => { const note = status === "needs_revision" ? window.prompt(lang === "en" ? "Revision note" : "Catatan revisi") : ""; if (status === "needs_revision" && !note) return; try { await api.patch(`/admin/governance/destinations/${item.id}/workflow`, { status, note }); toast.success(copy.published); load(); } catch (error) { toast.error(error.response?.data?.detail || t.common.error); } };
  const notify = async item => { try { const { data } = await api.post(`/admin/governance/partners/${item.id}/notify`); toast.success(`${copy.sent} ${data.deliveries.map(row => `${row.channel}: ${row.status}`).join(" · ")}`); load(); } catch (error) { toast.error(error.response?.data?.detail || t.common.error); } };
  const moderate = async (report, status, action = "none") => { const note = window.prompt(lang === "en" ? "Internal moderation note (optional)" : "Catatan moderasi internal (opsional)") || ""; try { await api.patch(`/admin/governance/reports/${report.id}`, { status, action, admin_note: note }); toast.success(copy.moderated); load(); } catch (error) { toast.error(error.response?.data?.detail || t.common.error); } };
  if (state === "loading") return <div className="p-8 text-sm text-inkSoft">{t.common.loading}</div>;
  if (state === "error") return <div className="p-8"><p className="text-red-700">{t.common.error}</p><button type="button" onClick={load} className="btn-outline mt-4"><RefreshCw className="h-4 w-4" />{copy.refresh}</button></div>;
  const summary = overview?.summary || {};
  return <div className="app-gutter w-full py-6 pb-16" data-testid="governance-page"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="eyebrow">Admin</div><h1 className="mt-2 font-display text-[26px] sm:text-4xl">{copy.title}</h1><p className="mt-2 max-w-3xl text-[13px] text-inkSoft">{copy.subtitle}</p></div><button type="button" onClick={load} className="btn-outline"><RefreshCw className="h-4 w-4" />{copy.refresh}</button></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[copy.quality, summary.quality_queue, ShieldCheck], [copy.stale, summary.stale, TriangleAlert], [copy.attention, summary.partner_attention, BellRing], [copy.reports, summary.open_reports, Flag]].map(([label, value, Icon]) => <article key={label} className="card-flat p-4"><Icon className="h-5 w-5 text-toba" /><div className="mt-3 text-xs text-inkSoft">{label}</div><strong className="text-3xl">{value || 0}</strong></article>)}</section>
    <section className="mt-7"><h2 className="font-display text-2xl">{copy.quality}</h2><div className="mt-3 space-y-3">{overview.quality_queue.length === 0 ? <div className="card-flat p-5 text-sm text-inkSoft">{copy.noData}</div> : overview.quality_queue.map(item => <article key={`${item.entity_type}-${item.id}`} className="card-flat p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-toba">{item.entity_type}</div><h3 className="font-semibold">{item.name}</h3><div className="mt-1 flex flex-wrap gap-2 text-xs text-inkSoft"><span>{item.completeness}% {copy.completeness}</span>{item.stale && <span className="text-amber-800">• {copy.stale}</span>}</div>{item.missing.length > 0 && <p className="mt-2 text-xs text-inkSoft">{copy.missing}: {item.missing.join(", ")}</p>}{item.source_label && <p className="mt-1 text-[11px] text-inkSoft">Source: {item.source_label}</p>}</div><div className="flex flex-wrap gap-2"><a href={item.preview_urls.id} target="_blank" rel="noreferrer" className="btn-outline"><Languages className="h-4 w-4" />{copy.openId}</a><a href={item.preview_urls.en} target="_blank" rel="noreferrer" className="btn-outline"><Languages className="h-4 w-4" />{copy.openEn}</a><a href={item.public_urls.id} target="_blank" rel="noreferrer" className="btn-outline"><Eye className="h-4 w-4" />{copy.direct}</a>{item.entity_type === "destination" && <><a href={`/admin/destinations/${item.id}/edit`} className="btn-outline">{copy.edit}</a><button type="button" onClick={() => workflow(item, "published")} className="btn-primary"><CheckCircle2 className="h-4 w-4" />{copy.publish}</button><button type="button" onClick={() => workflow(item, "needs_revision")} className="btn-outline">{copy.revision}</button></>}</div></div></article>)}</div></section>
    <section className="mt-8"><h2 className="font-display text-2xl">{copy.attention}</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{overview.partner_queue.length === 0 ? <div className="card-flat p-5 text-sm text-inkSoft">{copy.noData}</div> : overview.partner_queue.map(item => <article key={item.id} className="card-flat p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{item.business_name}</h3><p className="mt-1 text-xs text-inkSoft">{item.status} · {item.owner_email || "—"}</p>{item.revision_note && <p className="mt-2 text-xs text-amber-900">{item.revision_note}</p>}</div><button type="button" onClick={() => notify(item)} className="btn-primary"><Send className="h-4 w-4" />{copy.notify}</button></div></article>)}</div></section>
    <section className="mt-8"><h2 className="font-display text-2xl">{copy.reports}</h2><div className="mt-3 space-y-3">{reports.length === 0 ? <div className="card-flat p-5 text-sm text-inkSoft">{copy.noData}</div> : reports.slice(0, 100).map(report => <article key={report.id} className="card-flat p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider text-toba">{report.target_type} · {report.reason}</div><p className="mt-1 text-sm">{report.description || "—"}</p><p className="mt-1 text-xs text-inkSoft">{report.status} · {new Date(report.created_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{report.status === "open" && <button type="button" onClick={() => moderate(report, "investigating")} className="btn-outline">{copy.investigate}</button>}<button type="button" onClick={() => moderate(report, "resolved")} className="btn-outline">{copy.resolve}</button><button type="button" onClick={() => moderate(report, "dismissed")} className="btn-outline">{copy.dismiss}</button><button type="button" onClick={() => moderate(report, "resolved", "hide")} className="btn-outline text-red-700">{copy.hide}</button></div></div></article>)}</div></section>
    <AnalyticsGovernanceSection analytics={analytics} copy={copy} />
    <section className="mt-8 grid gap-5 xl:grid-cols-2"><div><h2 className="font-display text-2xl">{copy.delivery}</h2><div className="mt-3 card-flat divide-y divide-line">{notifications.slice(0, 20).map(row => <article key={`${row.channel}-${row.id}`} className="flex items-center gap-3 p-3 text-xs"><span className="w-14 font-semibold text-toba">{row.channel}</span><div className="min-w-0 flex-1"><div className="truncate">{row.kind} · {row.recipient}</div><div className="text-inkSoft">{row.created_at ? new Date(row.created_at).toLocaleString() : ""}</div></div><span className={`rounded-full px-2 py-1 font-semibold ${row.status === "sent" ? "bg-emerald-100 text-emerald-800" : row.status === "failed" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-900"}`}>{row.status}</span></article>)}</div></div><div><div className="flex items-center gap-2"><Scale className="h-5 w-5 text-toba" /><h2 className="font-display text-2xl">{copy.preview}</h2></div><p className="mt-1 text-xs text-inkSoft">{copy.roleHint}</p><select value={previewRole} onChange={event => setPreviewRole(event.target.value)} className="input-flat mt-3">{["guest", "user", "partner", "admin"].map(role => <option key={role}>{role}</option>)}</select>{rolePreview && <div className="card-flat mt-3 p-4 text-xs"><p className="font-semibold text-emerald-700">session_unchanged: {String(rolePreview.session_unchanged)}</p>{[[copy.routes, rolePreview.routes], [copy.capabilities, rolePreview.capabilities], [copy.restrictions, rolePreview.restrictions]].map(([title, values]) => <div key={title} className="mt-4"><h3 className="font-semibold">{title}</h3><div className="mt-2 flex flex-wrap gap-1.5">{values.map(value => <span key={value} className="chip min-h-0 px-2 py-1 text-[10px]">{value}</span>)}</div></div>)}</div>}</div></section>
  </div>;
}

function MetricGrid({ items, columns = "xl:grid-cols-4" }) {
  return <div className={`mt-3 grid gap-3 sm:grid-cols-2 ${columns}`}>
    {items.map(([label, value]) => <article key={label} className="card-flat p-4">
      <div className="text-xs text-inkSoft">{label}</div>
      <strong className="text-3xl">{value || 0}</strong>
    </article>)}
  </div>;
}

function AnalyticsGovernanceSection({ analytics, copy }) {
  const funnel = analytics?.funnel || {};
  const plannerFunnel = analytics?.planner_funnel || {};
  const health = analytics?.planner_health || {};
  const fairness = analytics?.fairness || {};
  const imageExposure = fairness.image_exposure || {};
  const flaggedScores = (fairness.equal_score_concentration || []).filter((row) => row.flagged);
  const overexposed = fairness.overexposed_partners || [];

  return <section className="mt-8" data-testid="governance-fairness-analytics">
    <div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-toba" /><h2 className="font-display text-2xl">{copy.analytics}</h2></div>
    <p className="mt-1 text-xs text-inkSoft">{copy.days}. {copy.consent}</p>

    <div className="mt-5 flex items-center gap-2"><h3 className="text-sm font-semibold text-ink">{copy.structuredHealth}</h3>{health.alert?.active && <span className="rounded-full bg-red-100 px-2 py-1 text-[10px] font-semibold text-red-800">Alert</span>}</div>
    {health.alert?.active && <div className="mt-3 flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-800" role="alert"><TriangleAlert className="h-4 w-4 shrink-0" />{copy.invalidAlert}</div>}
    {health.rollback?.recommended && <div className="mt-3 rounded-xl border border-red-300 bg-red-50 p-3 text-xs text-red-900" role="alert"><div className="flex gap-2 font-semibold"><TriangleAlert className="h-4 w-4 shrink-0" />{copy.rolloutRollback}</div><div className="mt-2 flex flex-wrap gap-1.5">{health.rollback.reasons.map((reason) => <span key={reason} className="rounded-full bg-white px-2 py-1 text-[10px]">{reason}</span>)}</div></div>}
    <MetricGrid items={[
      [copy.structuredRequests, health.structured_requests],
      [copy.structuredSuccess, health.structured_success],
      [copy.fallbacks, health.fallbacks],
      [copy.invalidRate, `${health.invalid_rate || 0}%`],
    ]} />
    <p className="mt-2 text-xs text-inkSoft">{copy.p95Duration}: {Math.round((health.performance?.p95_duration_ms || 0) / 1000)}s · {copy.p95Payload}: {Math.round((health.performance?.p95_payload_bytes || 0) / 1024)} KB</p>

    <h3 className="mt-5 text-sm font-semibold text-ink">{copy.plannerAnalytics}</h3>
    <MetricGrid items={[
      [copy.storySubmitted, plannerFunnel.planner_story_submitted],
      [copy.stepShown, plannerFunnel.planner_step_shown],
      [copy.stepCompleted, plannerFunnel.planner_step_completed],
      [copy.generated, plannerFunnel.planner_generated],
    ]} />

    <h3 className="mt-5 text-sm font-semibold text-ink">Mitra</h3>
    <MetricGrid columns="xl:grid-cols-5" items={[
      [copy.directory, funnel.directory_impression],
      [copy.ai, funnel.ai_impression],
      [copy.profileClicks, funnel.profile_click],
      [copy.profile, funnel.profile_view],
      [copy.contacts, funnel.whatsapp_click],
    ]} />

    <h3 className="mt-6 text-sm font-semibold text-ink">{copy.segments}</h3>
    <div className="card-flat mt-3 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b border-line text-inkSoft"><tr><th className="p-3">{copy.type}</th><th className="p-3">Tier</th><th className="p-3">Mitra</th><th className="p-3">Impressions</th><th className="p-3">AI</th><th className="p-3">WhatsApp</th><th className="p-3">Rate</th></tr></thead><tbody className="divide-y divide-line">{(fairness.by_type_tier || []).map((row) => <tr key={`${row.type}-${row.tier}`}><td className="p-3 font-semibold">{row.type}</td><td className="p-3">{row.tier === "featured" ? copy.featured : copy.regular}</td><td className="p-3">{row.partners_exposed}</td><td className="p-3">{row.impressions}</td><td className="p-3">{row.ai_impressions}</td><td className="p-3">{row.contacts}</td><td className="p-3">{row.contact_rate}%</td></tr>)}</tbody></table></div>

    <div className="mt-4 overflow-x-auto card-flat"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-line text-inkSoft"><tr><th className="p-3">Mitra</th><th className="p-3">{copy.type}</th><th className="p-3">Tier</th><th className="p-3">Directory</th><th className="p-3">AI</th><th className="p-3">{copy.profileClicks}</th><th className="p-3">WhatsApp</th><th className="p-3">{copy.score}</th><th className="p-3">{copy.factors}</th></tr></thead><tbody className="divide-y divide-line">{(analytics?.exposure || []).map((row) => <tr key={row.partner_id}><td className="p-3 font-semibold">{row.business_name}</td><td className="p-3">{row.type || "—"}</td><td className="p-3">{row.tier === "featured" ? copy.featured : copy.regular}</td><td className="p-3">{row.directory_impression}</td><td className="p-3">{row.ai_impression}</td><td className="p-3">{row.profile_click || 0}</td><td className="p-3">{row.whatsapp_click}</td><td className="p-3">{row.last_relevance_score || "—"}</td><td className="max-w-[260px] p-3 text-inkSoft">{row.match_factor_codes?.join(", ") || "—"}</td></tr>)}</tbody></table></div>

    <div className="mt-6 flex items-center gap-2"><Scale className="h-5 w-5 text-toba" /><h3 className="font-display text-xl">{copy.fairness}</h3></div>
    <div className="mt-3 grid gap-3 lg:grid-cols-2">
      <article className="card-flat p-4"><h4 className="text-sm font-semibold">{copy.rankingPolicy}</h4><p className="mt-2 text-xs leading-5 text-inkSoft">{copy.noSensitive}</p><div className="mt-3 flex flex-wrap gap-1.5">{(fairness.ranking_policy?.signals || []).map((signal) => <span key={signal} className="chip min-h-0 px-2 py-1 text-[10px]">{signal}</span>)}</div><p className="mt-3 text-xs text-inkSoft">Threshold: {fairness.ranking_policy?.relevance_threshold ?? "—"} · Featured cap/type: {fairness.ranking_policy?.featured_cap_per_type ?? "—"}</p></article>
      <article className="card-flat p-4"><h4 className="text-sm font-semibold">{copy.imageAudit}</h4><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><span className="text-inkSoft">With image</span><strong className="mt-1 block text-xl">{imageExposure.with_image_exposed || 0}/{imageExposure.with_image || 0}</strong><span className="text-inkSoft">{imageExposure.with_image_ai_impressions || 0} AI impressions</span></div><div><span className="text-inkSoft">Without image</span><strong className="mt-1 block text-xl">{imageExposure.without_image_exposed || 0}/{imageExposure.without_image || 0}</strong><span className="text-inkSoft">{imageExposure.without_image_ai_impressions || 0} AI impressions</span></div></div></article>
    </div>

    <div className={`mt-3 rounded-xl border p-3 text-xs ${flaggedScores.length || overexposed.length ? "border-amber-300 bg-amber-50 text-amber-950" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>
      <strong>{flaggedScores.length || overexposed.length ? copy.overexposed : copy.balanced}</strong>
      {flaggedScores.slice(0, 5).map((row) => <p key={`${row.type}-${row.tier}-${row.relevance_score}`} className="mt-1">{row.top_business_name}: {row.top_share_percentage}% @ score {row.relevance_score}</p>)}
      {overexposed.slice(0, 5).map((row) => <p key={row.partner_id} className="mt-1">{row.business_name}: {row.ai_impressions} AI impressions (median {row.segment_median})</p>)}
    </div>

    <h3 className="mt-6 text-sm font-semibold text-ink">{copy.gaps}</h3>
    <div className="card-flat mt-3 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="border-b border-line text-inkSoft"><tr><th className="p-3">{copy.area}</th><th className="p-3">{copy.type}</th><th className="p-3">{copy.emptyResults}</th></tr></thead><tbody className="divide-y divide-line">{(fairness.empty_results_by_area_type || []).slice(0, 30).map((row) => <tr key={`${row.area}-${row.type}`}><td className="p-3 font-semibold">{row.area}</td><td className="p-3">{row.type}</td><td className="p-3">{row.empty_results}</td></tr>)}</tbody></table></div>
  </section>;
}
