"""Milestone 7 end-to-end QA for admin CRUD, permissions, and secure LLM profiles.

Run against a local backend with REACT_APP_BACKEND_URL set. Every created record is
removed, including audit/AI logs generated by this suite.
"""

import json
import os
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import pytest
import requests
from bson import ObjectId
from pymongo import MongoClient


BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")
API = f"{BASE_URL}/api"
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "admin@wisatasumut.id")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "admin123")
PROVIDER_URL = "http://127.0.0.1:18082"


@pytest.fixture(scope="module")
def database():
    client = MongoClient(os.environ["MONGO_URL"])
    database = client[os.environ["DB_NAME"]]
    yield database
    client.close()


@pytest.fixture(scope="module")
def admin():
    session = requests.Session()
    response = session.post(f"{API}/auth/login", json={
        "email": ADMIN_EMAIL,
        "password": ADMIN_PASSWORD,
    })
    assert response.status_code == 200, response.text
    return session


class ProviderHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers.get("Content-Length", "0"))
        payload = json.loads(self.rfile.read(length) or b"{}")
        if self.path.startswith("/slow/"):
            time.sleep(22)
        if self.headers.get("Authorization") != "Bearer qa-valid-key":
            status, body = 401, {"error": "unauthorized"}
        elif payload.get("model") == "qa-wrong-model":
            status, body = 404, {"error": "model not found"}
        else:
            status, body = 200, {"choices": [{"message": {"content": "QA_OK"}}]}
        encoded = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        try:
            self.wfile.write(encoded)
        except BrokenPipeError:
            pass

    def log_message(self, *_args):
        return


@pytest.fixture(scope="module")
def llm_provider():
    server = ThreadingHTTPServer(("127.0.0.1", 18082), ProviderHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    yield
    server.shutdown()
    server.server_close()
    thread.join(timeout=2)


def assert_page(response):
    assert response.status_code == 200, response.text
    assert {"items", "total", "page", "page_size", "pages"} <= set(response.json())


def test_admin_permissions_are_enforced(database, admin):
    anonymous = requests.Session()
    assert anonymous.get(f"{API}/admin/settings").status_code == 401
    assert anonymous.get(f"{API}/admin/llm-profiles").status_code == 401

    email = f"qa-m7-{uuid.uuid4().hex[:10]}@example.com"
    user = requests.Session()
    registered = user.post(f"{API}/auth/register", json={
        "email": email, "password": "qa-password-123", "name": "QA M7 User", "accepted_terms": True,
    })
    assert registered.status_code == 200, registered.text
    try:
        for path in (
            "/admin/settings", "/admin/users", "/admin/destinations",
            "/admin/partners", "/admin/premium/plans", "/admin/llm-profiles",
            "/admin/audit-logs", "/admin/backups",
        ):
            assert user.get(f"{API}{path}").status_code == 403, path
        assert user.post(f"{API}/destinations", json={}).status_code == 403
        assert user.post(f"{API}/admin/email-templates", json={}).status_code == 403
    finally:
        database.users.delete_one({"email": email})


def test_admin_crud_and_server_side_lists(database, admin):
    suffix = uuid.uuid4().hex[:8]
    destination_id = partner_id = plan_id = template_id = user_id = None
    original_settings = admin.get(f"{API}/admin/settings").json()
    audit_before = set(database.audit_logs.distinct("_id"))
    system_before = set(database.system_logs.distinct("_id"))
    user_email = f"qa-crud-{suffix}@example.com"
    destination_payload = {
        "name": f"QA M7 Destination {suffix}", "name_en": "QA Destination",
        "location": "Medan", "category": "nature", "price": 10000,
        "description": "QA destination description long enough for validation.",
        "description_en": "QA destination description for validation.",
        "images": [], "video": "", "latitude": 3.5952, "longitude": 98.6722,
        "featured": False, "is_active": True,
    }
    partner_payload = {
        "business_name": f"QA M7 Partner {suffix}", "type": "guide",
        "whatsapp": "628123456789", "description": "QA partner description for validation.",
        "city": "Medan", "email": f"partner-{suffix}@example.com", "address": "Medan",
        "destination_ids": [], "image": "",
    }
    plan_payload = {
        "code": f"qa-{suffix}", "label_id": "QA Paket", "label_en": "QA Plan",
        "months": 2, "price": 123456, "active": True, "order": 90,
    }
    template_payload = {
        "key": f"qa_template_{suffix}", "name": "QA Template",
        "subject_id": "Subjek QA", "subject_en": "QA Subject",
        "body_id": "Isi email QA", "body_en": "QA email body", "enabled": True,
    }
    try:
        created = admin.post(f"{API}/destinations", json=destination_payload)
        assert created.status_code == 200, created.text
        destination_id = created.json()["id"]
        destination_payload["price"] = 15000
        assert admin.put(f"{API}/destinations/{destination_id}", json=destination_payload).json()["price"] == 15000
        toggled = admin.patch(f"{API}/destinations/{destination_id}/toggle-active")
        assert toggled.status_code == 200 and toggled.json()["is_active"] is False
        assert_page(admin.get(f"{API}/admin/destinations", params={"q": suffix, "status": "inactive"}))

        partner_payload["destination_ids"] = [destination_id]
        created = admin.post(f"{API}/partners/admin", json=partner_payload)
        assert created.status_code == 200, created.text
        partner_id = created.json()["id"]
        partner_payload["city"] = "Binjai"
        assert admin.put(f"{API}/partners/{partner_id}", json=partner_payload).json()["city"] == "Binjai"
        assert admin.patch(f"{API}/partners/{partner_id}/status", json={"status": "approved"}).status_code == 200
        assert admin.patch(f"{API}/partners/{partner_id}/toggle-active").json()["is_active"] is False
        assert_page(admin.get(f"{API}/admin/partners", params={"q": suffix, "approval": "approved", "status": "inactive"}))

        created = admin.post(f"{API}/admin/premium/plans", json=plan_payload)
        assert created.status_code == 200, created.text
        plan_id = created.json()["id"]
        plan_payload["price"] = 234567
        assert admin.put(f"{API}/admin/premium/plans/{plan_id}", json=plan_payload).json()["price"] == 234567
        assert_page(admin.get(f"{API}/admin/premium/plans", params={"q": suffix, "status": "active"}))

        created = admin.post(f"{API}/admin/email-templates", json=template_payload)
        assert created.status_code == 201, created.text
        template_id = created.json()["id"]
        template_payload["subject_en"] = "Updated QA Subject"
        assert admin.put(f"{API}/admin/email-templates/{template_id}", json=template_payload).json()["subject_en"] == "Updated QA Subject"
        assert admin.get(f"{API}/admin/email-templates/{template_id}").status_code == 200
        assert_page(admin.get(f"{API}/admin/email-templates", params={"q": suffix, "status": "enabled"}))

        user = requests.Session()
        registered = user.post(f"{API}/auth/register", json={
            "email": user_email, "password": "qa-password-123", "name": "QA CRUD User", "accepted_terms": True,
        })
        assert registered.status_code == 200
        row = database.users.find_one({"email": user_email})
        user_id = str(row["_id"])
        changed = admin.patch(f"{API}/admin/users/{user_id}", json={"role": "partner", "account_active": False})
        assert changed.status_code == 200 and changed.json()["role"] == "partner" and changed.json()["account_active"] is False
        assert_page(admin.get(f"{API}/admin/users", params={"q": user_email, "role": "partner", "status": "inactive"}))

        changed_settings = {**original_settings, "site_name": f"QA Site {suffix}"}
        changed_settings.pop("updated_at", None)
        changed_settings.pop("updated_by", None)
        assert admin.put(f"{API}/admin/settings", json=changed_settings).json()["site_name"] == f"QA Site {suffix}"
        for path in ("/admin/audit-logs", "/admin/ai-logs", "/admin/system-logs"):
            assert_page(admin.get(f"{API}{path}", params={"q": "QA", "date_from": "2020-01-01"}))
    finally:
        restore = {key: original_settings[key] for key in (
            "site_name", "support_email", "default_language", "maintenance_mode",
            "partner_review_sla_days", "planner_enabled", "backup_retention_days",
        )}
        admin.put(f"{API}/admin/settings", json=restore)
        if template_id:
            admin.delete(f"{API}/admin/email-templates/{template_id}")
        if plan_id:
            admin.delete(f"{API}/admin/premium/plans/{plan_id}")
        if partner_id:
            admin.delete(f"{API}/partners/{partner_id}")
        if destination_id:
            admin.delete(f"{API}/destinations/{destination_id}")
        if user_id:
            database.users.delete_one({"_id": ObjectId(user_id)})
        entity_ids = [value for value in (destination_id, partner_id, plan_id, template_id, user_id) if value]
        database.audit_logs.delete_many({"$or": [
            {"entity_id": {"$in": entity_ids}},
            {"details.name": {"$regex": f"QA M7 Destination {suffix}"}},
            {"details.business_name": {"$regex": f"QA M7 Partner {suffix}"}},
        ]})
        generated_audits = [value for value in database.audit_logs.distinct("_id") if value not in audit_before]
        generated_system_logs = [value for value in database.system_logs.distinct("_id") if value not in system_before]
        if generated_audits:
            database.audit_logs.delete_many({"_id": {"$in": generated_audits}})
        if generated_system_logs:
            database.system_logs.delete_many({"_id": {"$in": generated_system_logs}})


def test_backup_create_download_delete(database, admin):
    created = admin.post(f"{API}/admin/backups")
    assert created.status_code == 202, created.text
    backup_id = created.json()["id"]
    try:
        row = None
        for _ in range(40):
            response = admin.get(f"{API}/admin/backups", params={"q": created.json()["filename"], "page_size": 10})
            assert_page(response)
            items = response.json()["items"]
            row = next((item for item in items if item["id"] == backup_id), None)
            if row and row["status"] in {"completed", "error"}:
                break
            time.sleep(0.25)
        assert row and row["status"] == "completed", row
        downloaded = admin.get(f"{API}/admin/backups/{backup_id}/download")
        assert downloaded.status_code == 200
        assert downloaded.headers["content-type"].startswith("application/gzip")
    finally:
        deleted = admin.delete(f"{API}/admin/backups/{backup_id}")
        assert deleted.status_code == 200, deleted.text
        database.audit_logs.delete_many({"entity_type": "backup", "entity_id": backup_id})
        database.system_logs.delete_many({"source": "backup", "details.job_id": backup_id})


def test_secure_llm_profile_lifecycle(database, admin, llm_provider):
    suffix = uuid.uuid4().hex[:8]
    profile_ids = []
    try:
        unsafe = admin.post(f"{API}/admin/llm-profiles", json={
            "name": f"QA Unsafe {suffix}", "base_url": "ftp://127.0.0.1/model",
            "model_name": "qa-model", "enabled": True,
        })
        assert unsafe.status_code == 400

        secret = "qa-valid-key"
        created = admin.post(f"{API}/admin/llm-profiles", json={
            "name": f"QA LLM {suffix}", "base_url": f"{PROVIDER_URL}/v1",
            "model_name": "qa-model", "api_key": secret, "enabled": True,
        })
        assert created.status_code == 201, created.text
        profile_id = created.json()["id"]
        profile_ids.append(profile_id)
        assert secret not in created.text and "ciphertext" not in created.text and "nonce" not in created.text
        stored = database.llm_profiles.find_one({"_id": ObjectId(profile_id)})
        original_ciphertext = stored["api_key_ciphertext"]
        assert "api_key" not in stored and secret not in original_ciphertext

        base_payload = {
            "name": f"QA LLM {suffix}", "base_url": f"{PROVIDER_URL}/v1",
            "model_name": "qa-model", "enabled": True, "api_key_action": "preserve", "api_key": None,
        }
        preserved = admin.put(f"{API}/admin/llm-profiles/{profile_id}", json=base_payload)
        assert preserved.status_code == 200
        assert database.llm_profiles.find_one({"_id": ObjectId(profile_id)})["api_key_ciphertext"] == original_ciphertext

        wrong_key = {**base_payload, "api_key_action": "replace", "api_key": "qa-wrong-key"}
        rotated = admin.put(f"{API}/admin/llm-profiles/{profile_id}", json=wrong_key)
        assert rotated.status_code == 200 and "qa-wrong-key" not in rotated.text
        failed = admin.post(f"{API}/admin/llm-profiles/{profile_id}/test").json()
        assert failed["success"] is False and "401" in failed["error"]

        valid_key = {**base_payload, "api_key_action": "replace", "api_key": secret}
        assert admin.put(f"{API}/admin/llm-profiles/{profile_id}", json=valid_key).status_code == 200
        wrong_model = {**base_payload, "model_name": "qa-wrong-model"}
        assert admin.put(f"{API}/admin/llm-profiles/{profile_id}", json=wrong_model).status_code == 200
        failed = admin.post(f"{API}/admin/llm-profiles/{profile_id}/test").json()
        assert failed["success"] is False and "404" in failed["error"]

        assert admin.put(f"{API}/admin/llm-profiles/{profile_id}", json=base_payload).status_code == 200
        tested = admin.post(f"{API}/admin/llm-profiles/{profile_id}/test").json()
        assert tested["success"] is True
        assert admin.post(f"{API}/admin/llm-profiles/{profile_id}/activate").status_code == 200
        runtime = admin.get(f"{API}/admin/llm-profiles/runtime").json()
        assert runtime["source"] == "profile" and runtime["model_name"] == "qa-model"

        planner = requests.post(f"{API}/trip-planner/stream", json={
            "days": 1, "budget": 500000, "interests": ["nature"], "lang": "id",
        })
        assert planner.status_code == 200 and "QA_OK" in planner.text
        ai_logs = admin.get(f"{API}/admin/ai-logs", params={"q": "qa-model", "page_size": 5}).json()
        assert any(item["llm_source"] == "profile" and item["llm_model"] == "qa-model" for item in ai_logs["items"])

        duplicated = admin.post(f"{API}/admin/llm-profiles/{profile_id}/duplicate")
        assert duplicated.status_code == 201 and secret not in duplicated.text
        duplicate_id = duplicated.json()["id"]
        profile_ids.append(duplicate_id)
        removed = admin.put(f"{API}/admin/llm-profiles/{duplicate_id}", json={
            **base_payload, "name": f"QA LLM Removed {suffix}", "api_key_action": "remove",
        })
        assert removed.status_code == 200 and removed.json()["api_key_configured"] is False
        assert admin.post(f"{API}/admin/llm-profiles/{duplicate_id}/test").json()["success"] is False

        slow = admin.post(f"{API}/admin/llm-profiles", json={
            "name": f"QA LLM Slow {suffix}", "base_url": f"{PROVIDER_URL}/slow/v1",
            "model_name": "qa-model", "api_key": secret, "enabled": True,
        })
        assert slow.status_code == 201
        slow_id = slow.json()["id"]
        profile_ids.append(slow_id)
        timed_out = admin.post(f"{API}/admin/llm-profiles/{slow_id}/test").json()
        assert timed_out["success"] is False and "timed out" in timed_out["error"].lower()

        assert admin.delete(f"{API}/admin/llm-profiles/{profile_id}").status_code == 409
        fallback = admin.post(f"{API}/admin/llm-profiles/use-environment")
        assert fallback.status_code == 200 and fallback.json()["source"] == "environment"
    finally:
        admin.post(f"{API}/admin/llm-profiles/use-environment")
        for profile_id in reversed(profile_ids):
            admin.delete(f"{API}/admin/llm-profiles/{profile_id}")
        database.ai_planner_logs.delete_many({"llm_model": {"$in": ["qa-model", "qa-wrong-model"]}})
        database.audit_logs.delete_many({"$or": [
            {"entity_id": {"$in": profile_ids}},
            {"entity_type": "llm_environment", "details.previous_profile_id": {"$in": profile_ids}},
        ]})
