"""Persistence boundary for saved itinerary use cases."""

from typing import Any, Protocol


class ItineraryRepository(Protocol):
    async def active_destination_ids(self, values: list[str]) -> set[str]: ...

    async def eligible_partners(self, values: list[str]) -> list[dict[str, Any]]: ...

    async def active_offerings(
        self, partner_ids: list[str]
    ) -> list[dict[str, Any]]: ...

    async def destination_cards(self, values: list[str]) -> list[dict[str, Any]]: ...

    async def create(self, document: dict[str, Any]) -> dict[str, Any]: ...

    async def list_for_user(self, user_id: str) -> list[dict[str, Any]]: ...

    async def get(self, itinerary_id: str) -> dict[str, Any] | None: ...

    async def update_owned(
        self, itinerary_id: str, user_id: str, changes: dict[str, Any]
    ) -> dict[str, Any] | None: ...

    async def delete_owned(self, itinerary_id: str, user_id: str) -> bool: ...

    async def get_public(self, slug: str) -> dict[str, Any] | None: ...
