import React, { useCallback, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, CheckCircle2, Copy, KeyRound, Pencil, Play, Plus, Server, Trash2, Zap } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { ConfirmActionDialog, DataTable, DataTableToolbar, StatusBadge } from "../../../components/admin/index.js";
import { useLang } from "../../../contexts/LanguageContext.jsx";
import useAdminListParams from "../../../hooks/useAdminListParams.js";
import { formatError } from "../../../lib/api.js";
import { activateEnvironmentLlm, activateLlmProfile, deleteLlmProfile, duplicateLlmProfile, getLlmRuntime, listLlmProfiles, testLlmProfile } from "./settingsApi.js";

export default function LlmProfileListPage() {
  const { t } = useLang(); const copy = t.admin.settings; const qc = useQueryClient();
  const navigate = useNavigate();
  const { params, setParams, resetParams } = useAdminListParams({ defaultSort: "name" });
  const [confirm, setConfirm] = useState(null);
  const profiles = useQuery({ queryKey: ["admin", "llm", "profiles", params.q], queryFn: ({ signal }) => listLlmProfiles(params.q, signal) });
  const runtime = useQuery({ queryKey: ["admin", "llm", "runtime"], queryFn: ({ signal }) => getLlmRuntime(signal) });
  const refresh = async () => Promise.all([qc.invalidateQueries({ queryKey: ["admin", "llm"] }), qc.invalidateQueries({ queryKey: ["admin", "settings", "integrations"] })]);
  const testMutation = useMutation({ mutationFn: testLlmProfile, onSuccess: async (result) => { await refresh(); result.success ? toast.success(`${copy.testOk} · ${result.latency_ms} ms`) : toast.error(result.error || copy.actionError); }, onError: (e) => toast.error(formatError(e.response?.data?.detail || copy.actionError)) });
  const duplicateMutation = useMutation({ mutationFn: duplicateLlmProfile, onSuccess: async () => { await refresh(); toast.success(copy.duplicated); }, onError: (e) => toast.error(formatError(e.response?.data?.detail || copy.actionError)) });
  const confirmMutation = useMutation({ mutationFn: ({ kind, item }) => kind === "activate" ? activateLlmProfile(item.id) : kind === "environment" ? activateEnvironmentLlm() : deleteLlmProfile(item.id), onSuccess: async (_, variables) => { await refresh(); toast.success(variables.kind === "delete" ? copy.profileDeleted : copy.activated); setConfirm(null); }, onError: (e) => toast.error(formatError(e.response?.data?.detail || copy.actionError)) });
  const items = profiles.data || [];
  const healthLabel = useCallback((value) => value === "healthy" ? copy.healthy : value === "error" ? copy.error : copy.untested, [copy]);
  const columns = useMemo(() => [
    { key: "name", header: copy.name, render: (item) => <div className="min-w-[190px]"><div className="font-semibold flex items-center gap-2">{item.name}{item.active && <StatusBadge variant="success">{copy.active}</StatusBadge>}</div><div className="text-[11px] text-inkSoft mt-1 truncate max-w-[260px]">{item.base_url}</div></div> },
    { key: "model", header: copy.model, render: (item) => <code className="text-xs">{item.model_name}</code> },
    { key: "key", header: copy.apiKey, render: (item) => <span className="inline-flex gap-1.5 items-center text-xs"><KeyRound className="w-3.5 h-3.5" />{item.api_key_configured ? copy.keyReady : copy.noKey}</span> },
    { key: "health", header: copy.health, render: (item) => <div><StatusBadge variant={item.health_status === "healthy" ? "success" : item.health_status === "error" ? "danger" : "neutral"}>{healthLabel(item.health_status)}</StatusBadge>{item.latency_ms != null && <div className="text-[10px] text-inkSoft mt-1">{item.latency_ms} ms</div>}</div> },
    { key: "actions", header: "", mobile: false, cellClassName: "text-right", render: (item) => <div className="flex justify-end gap-1"><button type="button" className="btn-ghost px-2 text-[11px]" onClick={() => testMutation.mutate(item.id)} disabled={testMutation.isPending}><Zap className="w-3.5 h-3.5" />{copy.test}</button>{!item.active && <button type="button" className="w-9 h-9 rounded-lg hover:bg-line/30 inline-flex items-center justify-center" onClick={() => setConfirm({ kind: "activate", item })} aria-label={copy.activate}><Play className="w-4 h-4" /></button>}<button type="button" className="w-9 h-9 rounded-lg hover:bg-line/30 inline-flex items-center justify-center" onClick={() => duplicateMutation.mutate(item.id)} aria-label={copy.duplicate}><Copy className="w-4 h-4" /></button><Link className="w-9 h-9 rounded-lg hover:bg-line/30 inline-flex items-center justify-center" to={`/admin/settings/llm/${item.id}/edit`} aria-label={copy.edit}><Pencil className="w-4 h-4" /></Link><button type="button" disabled={item.active} className="w-9 h-9 rounded-lg hover:bg-red-50 text-red-700 disabled:opacity-30 inline-flex items-center justify-center" onClick={() => setConfirm({ kind: "delete", item })} aria-label={copy.remove}><Trash2 className="w-4 h-4" /></button></div> },
  ], [copy, duplicateMutation, healthLabel, testMutation]);
  return <div className="app-gutter w-full py-6 pb-16" data-testid="llm-profile-list-page">
    <header className="mb-5 flex items-end justify-between flex-wrap gap-3"><div><div className="eyebrow">Admin · Settings</div><h1 className="mt-2 font-display text-[26px] sm:text-4xl">{copy.llmTitle}</h1><p className="text-[13px] text-inkSoft mt-2">{copy.llmSub}</p></div><Link to="/admin/settings/llm/new" className="btn-primary"><Plus className="w-4 h-4" />{copy.addProfile}</Link></header>
    <section className="card-flat p-5 mb-4" aria-label={copy.runtime}><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3 items-center"><span className="w-11 h-11 rounded-xl bg-toba text-white flex items-center justify-center">{runtime.data?.source === "profile" ? <Activity className="w-5 h-5" /> : <Server className="w-5 h-5" />}</span><div><div className="text-[11px] uppercase tracking-wider text-inkSoft">{copy.runtime}</div><div className="font-semibold mt-1">{runtime.data?.profile_name || copy.environment}</div></div></div><div className="flex flex-wrap items-center gap-5 text-xs"><div><span className="text-inkSoft block">{copy.source}</span>{runtime.data?.source || "-"}</div><div><span className="text-inkSoft block">{copy.model}</span>{runtime.data?.model_name || "-"}</div><div><span className="text-inkSoft block">{copy.health}</span><span className="inline-flex items-center gap-1">{runtime.data?.health_status === "healthy" && <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />}{healthLabel(runtime.data?.health_status)}</span></div><div><span className="text-inkSoft block">{copy.latency}</span>{runtime.data?.latency_ms != null ? `${runtime.data.latency_ms} ms` : "-"}</div>{runtime.data?.source === "profile" && <button type="button" className="btn-outline px-3 text-xs" onClick={() => setConfirm({ kind: "environment", item: null })}>{copy.environment}</button>}</div></div></section>
    <DataTableToolbar searchValue={params.q} onSearchChange={(q) => setParams({ q: q.length >= 2 ? q : "" })} searchPlaceholder={copy.searchProfile} resultCount={profiles.isSuccess ? items.length : undefined} hasActiveFilters={Boolean(params.q)} onReset={resetParams} />
    {profiles.isError && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">{copy.loadError}</div>}
    <div className="mt-4"><DataTable columns={columns} items={items} loading={profiles.isLoading} hasActiveFilters={Boolean(params.q)} emptyTitle={copy.noProfiles} emptyDescription={copy.llmSub} caption={copy.llmTitle} onRowClick={(item) => navigate(`/admin/settings/llm/${item.id}/edit`)} /></div>
    <ConfirmActionDialog open={Boolean(confirm)} onOpenChange={(open) => !open && setConfirm(null)} title={confirm?.kind === "delete" ? copy.remove : confirm?.kind === "environment" ? copy.environment : copy.activate} description={confirm?.kind === "delete" ? copy.confirmDeleteProfile : confirm?.kind === "environment" ? copy.useEnvironment : copy.confirmActivate} confirmLabel={confirm?.kind === "delete" ? copy.remove : confirm?.kind === "environment" ? copy.environment : copy.activate} destructive={confirm?.kind === "delete"} loading={confirmMutation.isPending} onConfirm={() => confirmMutation.mutate(confirm)} />
  </div>;
}
