export const ADMIN_SETTINGS_TRANSLATIONS = {
  id: {
    generalTitle: "Pengaturan Umum", generalSub: "Atur identitas situs, operasi partner, planner, dan retensi backup.", integrationsTitle: "Status Integrasi", integrationsSub: "Status aman tanpa menampilkan credential atau API key.", llmTitle: "Konfigurasi LLM", llmSub: "Kelola endpoint OpenAI-compatible dan ganti model aktif tanpa restart backend.", templateTitle: "Template Email", templateSub: "Kelola konten email Indonesia dan Inggris dalam editor terpisah.", backupTitle: "Backup Database", backupSub: "Buat, cari, unduh, dan hapus snapshot database terkompresi.",
    addProfile: "Tambah profil", searchProfile: "Cari profil, model, atau Base URL...", environment: "Environment fallback", runtime: "Runtime aktif", source: "Sumber", model: "Model", latency: "Latensi", health: "Kesehatan", healthy: "Sehat", error: "Error", untested: "Belum diuji", active: "Aktif", inactive: "Nonaktif", enabled: "Diaktifkan", disabled: "Dinonaktifkan", keyReady: "API key tersimpan", noKey: "Tanpa API key", test: "Uji koneksi", activate: "Aktifkan", duplicate: "Duplikat", edit: "Edit", remove: "Hapus", confirmActivate: "Aktifkan profil ini untuk request AI Planner berikutnya?", confirmDeleteProfile: "Hapus profil LLM ini? Profil aktif tidak dapat dihapus.", testOk: "Koneksi LLM berhasil", profileSaved: "Profil LLM tersimpan", profileDeleted: "Profil LLM dihapus", duplicated: "Profil berhasil diduplikat", activated: "Profil aktif berhasil diganti", noProfiles: "Belum ada profil LLM.",
    name: "Nama profil", baseUrl: "Base URL", modelName: "Nama model", apiKey: "API key", apiKeyHint: "Write-only: nilai lama tidak pernah dikirim kembali ke browser.", keepKey: "Pertahankan key saat ini", replaceKey: "Ganti / rotasi key", removeKey: "Hapus key", newKey: "API key baru", confirmSecretChange: "Saya memahami perubahan key berlaku saat profil ini diaktifkan.", save: "Simpan profil", create: "Buat profil", back: "Kembali", loadError: "Data gagal dimuat", saveError: "Data gagal disimpan", actionError: "Aksi gagal diproses", unsaved: "Buang perubahan yang belum disimpan?", activeEditWarning: "Mengedit profil aktif akan mengembalikan runtime ke konfigurasi environment sampai profil diuji dan diaktifkan kembali.",
    addTemplate: "Tambah template", searchTemplate: "Cari key, nama, atau subjek...", key: "Key", templateName: "Nama", subject: "Subjek", updated: "Diperbarui", status: "Status", allStatus: "Semua status", deleteTemplate: "Hapus template email ini?", templateSaved: "Template email tersimpan", templateDeleted: "Template dihapus", noTemplates: "Belum ada template email.", subjectId: "Subjek (Indonesia)", subjectEn: "Subjek (Inggris)", bodyId: "Isi email (Indonesia)", bodyEn: "Isi email (Inggris)", preview: "Preview", editor: "Editor", discardTemplate: "Buang perubahan template yang belum disimpan?",
    createBackup: "Buat backup", searchBackup: "Cari filename atau pembuat...", filename: "Nama file", size: "Ukuran", documents: "Dokumen", createdBy: "Dibuat oleh", createdAt: "Dibuat", download: "Unduh", deleteBackup: "Hapus file backup ini?", backupStarted: "Backup dimulai", backupDeleted: "Backup dihapus", noBackups: "Belum ada backup.", directoryReady: "Direktori siap", processing: "Diproses", completed: "Selesai", pending: "Menunggu", useEnvironment: "Kembali gunakan konfigurasi LLM dari environment?",
    plannerCostControls: "Kontrol biaya AI Planner", plannerCostControlsSub: "Kuota diterapkan di server sebelum request LLM dimulai.", guestTrialEnabled: "Izinkan kuota gratis untuk pengunjung", guestGenerationLimit: "Batas pembuatan Guest", guestIdentityTtl: "Masa identitas Guest (hari)", guestIpDailyLimit: "Batas Guest per jaringan / hari", userDailyLimit: "Batas user terdaftar / hari (0 = tanpa batas)", generationCooldown: "Jeda antar-request (detik)", plannerResultRollout: "Rollout hasil AI Planner", plannerResultRolloutSub: "Aktifkan fitur dengan persentase 0% untuk QA internal Admin, lalu naikkan bertahap. Mematikan flag akan melakukan rollback untuk semua role, termasuk Admin.", plannerResultCards: "Destination dan partner cards", plannerPartnerMatches: "Pencocokan Mitra terstruktur", plannerCulinary: "Kategori Mitra Kuliner", plannerStructuredResults: "Structured result v2", plannerStructuredRollout: "Persentase rollout structured result", mitraRollout: "Rollout pengalaman Mitra", mitraRolloutSub: "Aktifkan bertahap dengan bucket akun yang stabil. Admin dapat mengakses ketika flag aktif; Mitra lama tidak kehilangan dashboard saat persentase berubah.", mitraOnboarding: "Onboarding Mitra baru", mitraDashboard: "Dashboard Mitra", rolloutEnabled: "Fitur diaktifkan", rolloutPercentage: "Persentase rollout",
  },
  en: {
    generalTitle: "General Settings", generalSub: "Manage site identity, partner operations, planner, and backup retention.", integrationsTitle: "Integration Status", integrationsSub: "Safe status overview without exposing credentials or API keys.", llmTitle: "LLM Configuration", llmSub: "Manage OpenAI-compatible endpoints and switch the active model without restarting the backend.", templateTitle: "Email Templates", templateSub: "Manage Indonesian and English email content in a dedicated editor.", backupTitle: "Database Backups", backupSub: "Create, search, download, and delete compressed database snapshots.",
    addProfile: "Add profile", searchProfile: "Search profile, model, or Base URL...", environment: "Environment fallback", runtime: "Active runtime", source: "Source", model: "Model", latency: "Latency", health: "Health", healthy: "Healthy", error: "Error", untested: "Untested", active: "Active", inactive: "Inactive", enabled: "Enabled", disabled: "Disabled", keyReady: "API key stored", noKey: "No API key", test: "Test connection", activate: "Activate", duplicate: "Duplicate", edit: "Edit", remove: "Delete", confirmActivate: "Activate this profile for the next AI Planner request?", confirmDeleteProfile: "Delete this LLM profile? The active profile cannot be deleted.", testOk: "LLM connection succeeded", profileSaved: "LLM profile saved", profileDeleted: "LLM profile deleted", duplicated: "Profile duplicated", activated: "Active profile switched", noProfiles: "No LLM profiles yet.",
    name: "Profile name", baseUrl: "Base URL", modelName: "Model name", apiKey: "API key", apiKeyHint: "Write-only: the existing value is never sent back to the browser.", keepKey: "Keep current key", replaceKey: "Replace / rotate key", removeKey: "Remove key", newKey: "New API key", confirmSecretChange: "I understand the key change applies when this profile is activated.", save: "Save profile", create: "Create profile", back: "Back", loadError: "Failed to load data", saveError: "Failed to save data", actionError: "Action failed", unsaved: "Discard unsaved changes?", activeEditWarning: "Editing an active profile returns runtime to the environment configuration until the profile is tested and activated again.",
    addTemplate: "Add template", searchTemplate: "Search key, name, or subject...", key: "Key", templateName: "Name", subject: "Subject", updated: "Updated", status: "Status", allStatus: "All statuses", deleteTemplate: "Delete this email template?", templateSaved: "Email template saved", templateDeleted: "Template deleted", noTemplates: "No email templates yet.", subjectId: "Subject (Indonesian)", subjectEn: "Subject (English)", bodyId: "Email body (Indonesian)", bodyEn: "Email body (English)", preview: "Preview", editor: "Editor", discardTemplate: "Discard unsaved template changes?",
    createBackup: "Create backup", searchBackup: "Search filename or creator...", filename: "Filename", size: "Size", documents: "Documents", createdBy: "Created by", createdAt: "Created", download: "Download", deleteBackup: "Delete this backup file?", backupStarted: "Backup started", backupDeleted: "Backup deleted", noBackups: "No backups yet.", directoryReady: "Directory ready", processing: "Processing", completed: "Completed", pending: "Pending", useEnvironment: "Return to the environment LLM configuration?",
    plannerCostControls: "AI Planner cost controls", plannerCostControlsSub: "Quotas are enforced on the server before an LLM request starts.", guestTrialEnabled: "Allow a free guest quota", guestGenerationLimit: "Guest generation limit", guestIdentityTtl: "Guest identity lifetime (days)", guestIpDailyLimit: "Guest limit per network / day", userDailyLimit: "Registered user limit / day (0 = unlimited)", generationCooldown: "Delay between requests (seconds)", plannerResultRollout: "AI Planner result rollout", plannerResultRolloutSub: "Enable a feature at 0% for internal Admin QA, then increase it gradually. Turning the flag off rolls it back for every role, including Admin.", plannerResultCards: "Destination and partner cards", plannerPartnerMatches: "Structured Mitra matching", plannerCulinary: "Culinary Mitra category", plannerStructuredResults: "Structured result v2", plannerStructuredRollout: "Structured result rollout percentage", mitraRollout: "Mitra experience rollout", mitraRolloutSub: "Release gradually using stable account buckets. Admins can access enabled flags; existing partners keep dashboard access when percentages change.", mitraOnboarding: "New Mitra onboarding", mitraDashboard: "Mitra dashboard", rolloutEnabled: "Feature enabled", rolloutPercentage: "Rollout percentage",
  },
};

export const ADMIN_LOG_TRANSLATIONS = {
  id: { auditTitle: "Audit Trail", auditSub: "Riwayat aksi admin terhadap data dan konfigurasi.", aiTitle: "Log AI Planner", aiSub: "Pantau request, runtime LLM, durasi, dan kegagalan planner.", systemTitle: "System Logs", systemSub: "Peristiwa operasional backend yang sudah melalui redaksi secret.", search: "Cari isi log...", filters: "Filter", dateFrom: "Dari tanggal", dateTo: "Sampai tanggal", all: "Semua", time: "Waktu", admin: "Admin", action: "Aksi", entity: "Entitas", status: "Status", request: "Request", model: "Model / Sumber", duration: "Durasi", level: "Level", source: "Sumber", message: "Pesan", details: "Detail log", empty: "Belum ada log.", reset: "Reset", language: "Bahasa", refresh: "Muat ulang", loadError: "Log gagal dimuat", viewDetails: "Lihat detail log", days: "hari", catalogShort: "katalog" },
  en: { auditTitle: "Audit Trail", auditSub: "History of administrator actions on data and configuration.", aiTitle: "AI Planner Logs", aiSub: "Monitor requests, LLM runtime, duration, and planner failures.", systemTitle: "System Logs", systemSub: "Backend operational events after secret redaction.", search: "Search log content...", filters: "Filters", dateFrom: "From date", dateTo: "To date", all: "All", time: "Time", admin: "Admin", action: "Action", entity: "Entity", status: "Status", request: "Request", model: "Model / Source", duration: "Duration", level: "Level", source: "Source", message: "Message", details: "Log details", empty: "No logs yet.", reset: "Reset", language: "Language", refresh: "Refresh", loadError: "Failed to load logs", viewDetails: "View log details", days: "days", catalogShort: "catalog" },
};
